# Generated by Django 4.1.13 on 2024-06-01 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_alter_user_address_alter_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_info.address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_info.fullname'),
        ),
    ]
