# Generated by Django 4.1.13 on 2024-05-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.PositiveIntegerField()),
                ('doctor_id', models.PositiveIntegerField()),
                ('appointment_id', models.PositiveIntegerField()),
                ('details', models.TextField()),
                ('prescription_id', models.PositiveIntegerField(blank=True, null=True)),
                ('medical_supplies_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medical_record',
            },
        ),
    ]
