# Generated by Django 4.1.13 on 2024-06-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.PositiveBigIntegerField()),
                ('dosage', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=255)),
                ('medication_id', models.ManyToManyField(to='medications.medication')),
            ],
            options={
                'db_table': 'prescription',
            },
        ),
    ]
